/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAuthorsRouteImport } from './routes/_app/authors'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppLoansRouteImport } from './routes/_app/loans'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBookBook_idRouteImport } from './routes/_app/book.$book_id'
import { Route as AppLibrarySearchRouteImport } from './routes/_app/library.search'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorsRoute = AppAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBookBook_idRoute = AppBookBook_idRouteImport.update({
  id: '/book/$book_id',
  path: '/book/$book_id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibrarySearchRoute = AppLibrarySearchRouteImport.update({
  id: '/library/search',
  path: '/library/search',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/authors': typeof AppAuthorsRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/loans': typeof AppLoansRoute
  '/locations': typeof AppLocationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/book/$book_id': typeof AppBookBook_idRoute
  '/library/search': typeof AppLibrarySearchRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/authors': typeof AppAuthorsRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/loans': typeof AppLoansRoute
  '/locations': typeof AppLocationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/book/$book_id': typeof AppBookBook_idRoute
  '/library/search': typeof AppLibrarySearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/authors': typeof AppAuthorsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/book/$book_id': typeof AppBookBook_idRoute
  '/_app/library/search': typeof AppLibrarySearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/authors'
    | '/categories'
    | '/customers'
    | '/loans'
    | '/locations'
    | '/profile'
    | '/settings'
    | '/book/$book_id'
    | '/library/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/authors'
    | '/categories'
    | '/customers'
    | '/loans'
    | '/locations'
    | '/profile'
    | '/settings'
    | '/'
    | '/book/$book_id'
    | '/library/search'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/authors'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/loans'
    | '/_app/locations'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/'
    | '/_app/book/$book_id'
    | '/_app/library/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authors': {
      id: '/_app/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AppAuthorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$book_id': {
      id: '/_app/book/$book_id'
      path: '/book/$book_id'
      fullPath: '/book/$book_id'
      preLoaderRoute: typeof AppBookBook_idRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/search': {
      id: '/_app/library/search'
      path: '/library/search'
      fullPath: '/library/search'
      preLoaderRoute: typeof AppLibrarySearchRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuthorsRoute: typeof AppAuthorsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppLoansRoute: typeof AppLoansRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookBook_idRoute: typeof AppBookBook_idRoute
  AppLibrarySearchRoute: typeof AppLibrarySearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuthorsRoute: AppAuthorsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppLoansRoute: AppLoansRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookBook_idRoute: AppBookBook_idRoute,
  AppLibrarySearchRoute: AppLibrarySearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
